// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQfszEs3ic3S1caMMHmUfhjDPsX6VlZvs',
    appId: '1:844292071989:web:30b21be7ac26b096af077c',
    messagingSenderId: '844292071989',
    projectId: 'meowdical-3b435',
    authDomain: 'meowdical-3b435.firebaseapp.com',
    storageBucket: 'meowdical-3b435.appspot.com',
    measurementId: 'G-YYKVJMPYJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW4ogR53QLHObL6zqXkvpbkMa43oO8gj4',
    appId: '1:844292071989:android:3a508e2ec58e950baf077c',
    messagingSenderId: '844292071989',
    projectId: 'meowdical-3b435',
    storageBucket: 'meowdical-3b435.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiGdvoJq_tcHgm4NBgymR2RrNVElhtUmM',
    appId: '1:844292071989:ios:2603502c9551cc1eaf077c',
    messagingSenderId: '844292071989',
    projectId: 'meowdical-3b435',
    storageBucket: 'meowdical-3b435.appspot.com',
    iosBundleId: 'com.example.meowdical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiGdvoJq_tcHgm4NBgymR2RrNVElhtUmM',
    appId: '1:844292071989:ios:1778495bc434bbe4af077c',
    messagingSenderId: '844292071989',
    projectId: 'meowdical-3b435',
    storageBucket: 'meowdical-3b435.appspot.com',
    iosBundleId: 'com.example.meowdical.RunnerTests',
  );
}
